// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: genericmessage.proto

package saramaprotobuf

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GenericMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Set of FileDescriptorProtos which describe the type and its dependencies.
	DescriptorSet *descriptor.FileDescriptorSet `protobuf:"bytes,1,opt,name=descriptor_set,json=descriptorSet,proto3" json:"descriptor_set,omitempty"`
	// The message and its type, encoded as an Any message.
	Message *any.Any `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GenericMessage) Reset() {
	*x = GenericMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genericmessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericMessage) ProtoMessage() {}

func (x *GenericMessage) ProtoReflect() protoreflect.Message {
	mi := &file_genericmessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericMessage.ProtoReflect.Descriptor instead.
func (*GenericMessage) Descriptor() ([]byte, []int) {
	return file_genericmessage_proto_rawDescGZIP(), []int{0}
}

func (x *GenericMessage) GetDescriptorSet() *descriptor.FileDescriptorSet {
	if x != nil {
		return x.DescriptorSet
	}
	return nil
}

func (x *GenericMessage) GetMessage() *any.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_genericmessage_proto protoreflect.FileDescriptor

var file_genericmessage_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x61, 0x72, 0x61, 0x6d, 0x61, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x49, 0x0a, 0x0e, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x53,
	0x65, 0x74, 0x52, 0x0d, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x53, 0x65,
	0x74, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_genericmessage_proto_rawDescOnce sync.Once
	file_genericmessage_proto_rawDescData = file_genericmessage_proto_rawDesc
)

func file_genericmessage_proto_rawDescGZIP() []byte {
	file_genericmessage_proto_rawDescOnce.Do(func() {
		file_genericmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_genericmessage_proto_rawDescData)
	})
	return file_genericmessage_proto_rawDescData
}

var file_genericmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_genericmessage_proto_goTypes = []interface{}{
	(*GenericMessage)(nil),               // 0: saramaprotobuf.GenericMessage
	(*descriptor.FileDescriptorSet)(nil), // 1: google.protobuf.FileDescriptorSet
	(*any.Any)(nil),                      // 2: google.protobuf.Any
}
var file_genericmessage_proto_depIdxs = []int32{
	1, // 0: saramaprotobuf.GenericMessage.descriptor_set:type_name -> google.protobuf.FileDescriptorSet
	2, // 1: saramaprotobuf.GenericMessage.message:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_genericmessage_proto_init() }
func file_genericmessage_proto_init() {
	if File_genericmessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_genericmessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_genericmessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_genericmessage_proto_goTypes,
		DependencyIndexes: file_genericmessage_proto_depIdxs,
		MessageInfos:      file_genericmessage_proto_msgTypes,
	}.Build()
	File_genericmessage_proto = out.File
	file_genericmessage_proto_rawDesc = nil
	file_genericmessage_proto_goTypes = nil
	file_genericmessage_proto_depIdxs = nil
}
